openapi: 3.0.0
info:
  version: '1.0'
  title: CFBA_Predictor
  description: >-
    API to predict college football games based on attendance and fill rate.
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: College Football Attendance Predictor
  license:
    name: Apache
paths:
  /predict/{id}:
    get:
      tags:
        - Prediction
      operationId: prediction.my_prediction
      description: Returns predicted attendance based off two list values given
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: array
            items:
              type: number
            minItems: 1
          style: simple
          explode: true
        - in: query
          name: metadata
          schema:
            type: boolean
      responses:
        '200':
          description: 'Predicted attendance'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Predict'
                
  #/model/{metric}:
 #   get:
 #     tags:
 #       - Stats
 #     operationId: prediction.my_model
 #     description: Returns valuable metrics about the model in use.
 #     parameters:
 #       - in: path
 #         name: metric
 #         required: true
#          schema:
 #           type: array
#            items:
 #             type: number
 #           minItems: 1
 #         style: simple
 #         explode: true
 #       - in: query
 #         name: metadata
 #         schema:
 #           type: boolean
#      responses:
 #       '200':
 #         description: 'allows you to enter MSE, RMSE, or MAE keywords to return'
#          content:
#            application/json:
#              schema:
 #               $ref: '#/components/schemas/Model'
 
  /dataset/<filename>:
    get:
      tags:
        - Download
      summary: Allows you to download the dataset that was used in the model.
      operationId: file.download
      responses:
        '405':
          description: Invalid input
servers:
  - url: 'http://localhost:8080/engr-222'
components:
  schemas:
    Predict:
      type: object
      required:
        - model
      properties:
        model:
          type: string
    Model:
      type: object
      required:
        - model
      properties:
        model:
          type: string